/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.gradleproject1;

import javafx.application.Application;
import static javafx.application.Application.launch;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.scene.text.Text;
/**
 *
 * @author munkaransingh
 */

public class App extends Application{

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        
        // TODO code application logic here
        launch(args);
    }
    
    public void start(Stage primaryStage) {
	try {
                Parent root = FXMLLoader.load(getClass().getClassLoader().getResource("WeatherApplication.fxml"));
		Scene scene = new Scene(root);
		primaryStage.setTitle("M&M Weather");
		primaryStage.setScene(scene);
		primaryStage.show();
	} 
        catch(Exception e) {
		e.printStackTrace();
	}
                
    }
    
}